name: navigate_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/navigate_core
  - apps/navigate

dev_dependencies:
  melos: ^7.5.1

melos:
  repository: https://github.com/rgdevment/NaviGate

  scripts:
    analyze:
      exec: dart analyze --fatal-infos
      description: Run dart analyze in all packages

    format:
      exec: dart format .
      description: Run dart format in all packages

    test:
      exec: dart test
      description: Run tests in all packages
      packageFilters:
        dirExists: test

    clean:
      exec: flutter clean
      description: Clean build artifacts in all packages
