include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error

linter:
  rules:
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_dynamic_calls
    - prefer_single_quotes
    - sort_child_properties_last
    - use_super_parameters
    - unnecessary_late
