import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:window_manager/window_manager.dart';

import 'l10n/app_localizations.dart';
import 'providers.dart';
import 'ui/picker/picker_window.dart';
import 'ui/settings/settings_window.dart';
import 'ui/shared/app_theme.dart';

final class NavigateApp extends ConsumerStatefulWidget {
  const NavigateApp({super.key});

  @override
  ConsumerState<NavigateApp> createState() => _NavigateAppState();
}

final class _NavigateAppState extends ConsumerState<NavigateApp>
    with WindowListener {
  // Settle window for the picker. Showing a window programmatically produces a
  // focus/blur burst of its own — `show()` is posted asynchronously on Windows
  // while `focus()` is not — so a blur arriving inside this window is the
  // activation settling, not the user clicking away.
  //
  // The timer is the *only* thing that arms the guard. It used to be armed on
  // the first onWindowFocus as well, which meant the focus event generated by
  // showing the window armed it immediately and the very next blur closed the
  // picker before the user could click anything.
  static const _pickerSettleDelay = Duration(milliseconds: 350);
  bool _pickerBlurReady = false;
  Timer? _blurGuardTimer;

  // Debounce: skip provider invalidation if we invalidated less than 2s ago.
  DateTime? _lastFocusInvalidation;

  @override
  void initState() {
    super.initState();
    windowManager.addListener(this);
    // A cold start that carries a URL builds this widget already in picker
    // mode, so the listener below never fires for it. Without arming here the
    // picker could never be dismissed by clicking away.
    if (ref.read(appStateProvider).mode == AppMode.picker) _armBlurGuard();
  }

  @override
  void dispose() {
    _blurGuardTimer?.cancel();
    windowManager.removeListener(this);
    super.dispose();
  }

  void _armBlurGuard() {
    _blurGuardTimer?.cancel();
    _pickerBlurReady = false;
    _blurGuardTimer = Timer(_pickerSettleDelay, () {
      _pickerBlurReady = true;
    });
  }

  @override
  void onWindowClose() async {
    await windowManager.hide();
    ref.read(appStateProvider.notifier).hide();
  }

  @override
  void onWindowFocus() {
    final now = DateTime.now();
    if (_lastFocusInvalidation == null ||
        now.difference(_lastFocusInvalidation!) >= const Duration(seconds: 2)) {
      _lastFocusInvalidation = now;
      ref.invalidate(isDefaultBrowserProvider);
      ref.invalidate(isStartupEnabledProvider);
    }
  }

  @override
  void onWindowBlur() {
    if (ref.read(appStateProvider).mode != AppMode.picker) return;
    if (!_pickerBlurReady) return;
    ref.read(appStateProvider.notifier).hide();
  }

  @override
  Widget build(BuildContext context) {
    final appState = ref.watch(appStateProvider);
    final locale = ref.watch(localeProvider);
    final themeMode = ref.watch(themeModeProvider);

    // Window geometry and visibility are driven exclusively from bootstrap's
    // serialised transition queue. A second show()/focus() from here raced it
    // one frame later and could leave the window on screen after the state had
    // already collapsed back to hidden — a visible frame with no content.
    ref.listen<AppState>(appStateProvider, (prev, next) {
      if (prev?.mode == next.mode) return;
      if (next.mode == AppMode.picker) {
        _armBlurGuard();
      } else {
        _blurGuardTimer?.cancel();
        _pickerBlurReady = false;
      }
    });

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: themeMode,
      locale: locale,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      home: switch (appState.mode) {
        AppMode.hidden => const _HiddenGuard(),
        AppMode.settings => const SettingsWindow(),
        AppMode.picker => PickerWindow(
          url: appState.pendingUrl ?? '',
          origin: appState.pendingOrigin,
        ),
      },
    );
  }
}

/// What the user sees if the window is ever visible while the app believes it
/// is hidden: an empty dark rectangle — the reported "just the frame".
///
/// Rather than only painting that rectangle, this reconciles the window with
/// the state, so any remaining race resolves itself on the next frame instead
/// of leaving an empty window on screen.
final class _HiddenGuard extends StatefulWidget {
  const _HiddenGuard();

  @override
  State<_HiddenGuard> createState() => _HiddenGuardState();
}

final class _HiddenGuardState extends State<_HiddenGuard> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      try {
        if (await windowManager.isVisible()) await windowManager.hide();
      } on Object {
        // Best-effort reconciliation; the window plugin may be unavailable.
      }
    });
  }

  @override
  Widget build(BuildContext context) =>
      const ColoredBox(color: Color(0xFF1E1E2E));
}
