name: Update Downloads Badge

on:
    schedule:
        - cron: "0 */12 * * *"
    workflow_dispatch:

jobs:
    update-badge:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v6

            - name: Setup uv
              uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: false

            - name: Update downloads badge
              env:
                  GITHUB_TOKEN: ${{ github.token }}
                  GIST_ID: ${{ vars.GIST_ID }}
                  GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
                  STORE_TENANT_ID: ${{ secrets.STORE_TENANT_ID }}
                  STORE_CLIENT_ID: ${{ secrets.STORE_CLIENT_ID }}
                  STORE_CLIENT_SECRET: ${{ secrets.STORE_CLIENT_SECRET }}
                  STORE_APP_ID: ${{ vars.STORE_APP_ID }}
              run: uv run resources/scripts/update_badge.py
